config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 1000 },
                      presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: 'hello, world!'
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[show edit update destroy]

  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show; end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit; end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to root_path, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to micropost_url(@micropost), notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy!

    respond_to do |format|
      format.html do
        redirect_to root_path, notice: 'Micropost was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_micropost
    @micropost = Micropost.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def micropost_params
    params.require(:micropost).permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  # before_action :set_microposts, only: %i[show]

  # GET /users or /users.json
  def index
    @users = User.all
    @microposts = Micropost.all
    @micropost = Micropost.new
  end

  # GET /users/1 or /users/1.json
  def show
    @user_microposts = Micropost.all.each_with_object([]) do |micropost, microposts|
      microposts << micropost if micropost.user_id == @user.id
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!
    Micropost.destroy_by(user_id: @user.id)

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # def set_microposts
  #   @micropost =
  # end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Troll Deck</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
      href="https://fonts.googleapis.com/css2?family=Bungee+Shade&display=swap"
      rel="stylesheet"
    >
  </head>

  <body class='bg-black text-white'>
    <main class="container mx-auto px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, 
              class: "border-[1px] border-solid border-l-0 border-r-0 border-b-0
              border-gray-700 ") do |form| %>
  <% if micropost.errors.any? %>
    <div
      id="error_explanation"
      class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3"
    >
      <h2><%= pluralize(micropost.errors.count, "error") %>
        prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='flex p-5 gap-2'>
    <div class='w-full'>
      <div class="">
        <%= form.text_area :content,
                       rows: 2,
                       class:
                         "w-full outline-none text-white bg-black border-1 border-solid border-black text-xl",
                       placeholder: "What is happening?!" %>
      </div>

      <div class="flex justify-end items-center gap-2 py-2">
        <%= form.select :user_id,
                    User.all.reverse.map { |user| [user.name, user.id] },
                    {},
                    class:
                      "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 w-full text-white bg-black border-[1px] border-solid border-gray-700" %>
        <div class="">
          <%= form.submit value: "Post",
                      class:
                        "rounded-3xl py-2 px-5 bg-[#1D9AF1] text-white inline-block font-medium cursor-pointer" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div id="<%= dom_id micropost %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= micropost.content %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= micropost.user_id %>
  </p>

</div>

app/views/microposts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing micropost</h1>

  <%= render "form", micropost: @micropost %>

  <%= link_to "Show this micropost", @micropost, class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
  <%= link_to "Back to microposts", microposts_path, class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
</div>

app/views/microposts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Microposts" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Microposts</h1>
    <%= link_to "New micropost", new_micropost_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="microposts" class="min-w-full">
    <% @microposts.each do |micropost| %>
      <%= render micropost %>
      <p>
        <%= link_to "Show this micropost", micropost, class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/microposts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New micropost</h1>

  <%= render "form", micropost: @micropost %>

  <%= link_to "Back to users",
  users_path,
  class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
</div>

app/views/microposts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p
        class="
          py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
        "
        id="notice"
      ><%= notice %></p>
    <% end %>

    <%= render @micropost %>

    <%= link_to "Edit this micropost",
    edit_micropost_path(@micropost),
    class: "mt-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
    <%= link_to "Back to users",
    users_path,
    class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this micropost",
      @micropost,
      method: :delete,
      class: "mt-2 rounded-lg py-3 px-5 bg-[#1E283A] font-medium" %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div
      id="error_explanation"
      class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3"
    >
      <h2><%= pluralize(user.errors.count, "error") %>
        prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name,
                    class:
                      "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-gray-900" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email,
                    class:
                      "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full text-gray-900" %>
  </div>

  <div class="inline">
    <%= form.submit class:
                  "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class='flex flex-col py-4'>
  <span class="text-sm text-gray-500">
    <%= user.email %>
  </span>

  <span class="font-bold">
    <%= link_to "#{user.name}", user, class: "font-medium hover:text-[#1D9AF1]" %>
  </span>

  <span class='text-sm text-gray-500'>
    <%= "#{user.microposts.length == 1 ? user.microposts.length.to_s + " post" : user.microposts.length.to_s + " posts"}" %>
  </span>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <div class='sm:px-0 md:px-0 lg:px-40 flex justify-between gap-8'>
    <% content_for :title, "Users", class: "text-2xl" %>
    <!-- nav -->
    <div class='sm:w-[10%] md:w-[10%] lg:w-[25%] flex flex-col gap-8 pt-4'>
      <h1 class="sm:hidden md:hidden lg:block logo font-bold text-5xl">
        Troll Deck
      </h1>
      <div
        class='
          sm:block md:block lg:hidden text-5xl flex sm:justify-center md:justify-center
          lg:justify-start
        '
      >
        <i class="fa-solid fa-skull"></i>
      </div>
      <p class='sm:hidden md:hidden lg:block font-medium text-md text-gray-500 pb-5'>
        Troll Deck is a onestop shop for your trolling needs. Draft microposts
        as multiple users, then regret it after.
      </p>
      <div
        class='
          flex flex-col sm:items-center md:items-center lg:items-start gap-4 text-xl
          font-bold
        '
      >
        <div class='flex gap-2 items-center hover:text-[#1D9AF1]'>
          <i class="sm:text-2xl md:text-2xl lg:text-xl fa-solid fa-book-skull pr-1"></i>
          <%= link_to "New micropost",
          new_micropost_path,
          class: "sm:hidden md:hidden lg:inline-block" %>
        </div>
        <div class='flex gap-2 items-center hover:text-[#1D9AF1]'>
          <i class="sm:text-xl md:text-xl lg:text-lg fa-solid fa-user-plus"></i>
          <%= link_to "New troll", new_user_path, class: "sm:hidden md:hidden lg:inline-block" %>
        </div>
      </div>

    </div>
    <!-- feed -->
    <div
      id="microposts"
      class="
        sm:w-full md:w-full lg:w-[60%] h-full border-[1px] border-solid border-gray-700
        border-t-0
      "
    >
      <div class='h-[3rem] flex justify-center items-center'>
        <div
          class='
            h-full border-4 border-solid border-[#1D9AF1] border-l-0 border-r-0 border-t-0
            flex items-center
          '
        >
          <h2 class='text-xl font-bold'>
            Your microposts
          </h2>
        </div>
      </div>
      <%= render "microposts/form", micropost: @micropost %>
      <% if @microposts.empty? %>
        <p
          class='
            text-white text-center border-[1px] border-solid border-gray-700 border-l-0
            border-r-0 border-b-0 pt-4
          '
        >No one's written any posts.</p>
      <% else %>
        <% @microposts.reverse.each do |micropost| %>
          <div
            class='
              p-5 border-[1px] border-solid border-l-0 border-r-0 border-b-0 border-gray-700
              flex gap-4
            '
          >
            <div
              class='
                min-w-[2.5rem] h-[2.5rem] rounded-[50%] bg-[#1D9AF1] flex justify-center
                items-center
              '
            >
              <%= link_to "#{User.find_by(id: micropost.user_id).name[0]}",
              User.find_by(id: micropost.user_id),
              class: "logo text-xl text-white font-bold" %>
            </div>
            <div class='flex flex-col flex-grow'>
              <div class='flex gap-2 items-center'>
                <span class='font-bold pb-1'>
                  <%= link_to "#{User.find_by(id: micropost.user_id).name}",
                  User.find_by(id: micropost.user_id),
                  class: "font-medium hover:text-[#1D9AF1]" %>
                </span>
                <span class='text-sm text-gray-500'>
                  <%= if micropost.created_at.to_s.split(" ")[0] == Time.now.to_s.slice(0, 10)
                    "Today, #{micropost.created_at.to_s.split(" ").drop(1).join(" ")}"
                  else
                    micropost.created_at
                  end %>
                </span>
              </div>
              <p class='text-sm'><%= micropost.content %></p>
              <div class='flex gap-2 font-medium'>
                <%= link_to "Edit",
                edit_micropost_path(micropost),
                class: "text-sm text-gray-500 underline pt-3 hover:text-[#1D9AF1]" %>
                <%= button_to "Destroy",
                micropost,
                method: :delete,
                class: "text-sm text-gray-500 underline pt-3 hover:text-red-800" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if @microposts.length >= 1 %>
        <div
          class='
            border-[1px] border-solid border-gray-700 border-l-0 border-r-0 border-b-0
            text-center p-5
          '
        >
          Oops No more posts...
        </div>
      <% end %>
    </div>
    <!-- users -->
    <div class='flex flex-col w-[35%] h-full sm:hidden md:hidden lg:block'>
      <div
        class="
          p-5 rounded-2xl border-[1px] border-solid border-gray-700 mt-4 flex flex-col
          gap-4
        "
      >
        <div class='flex gap-2 items-center'>
          <i class="fa-solid fa-chart-line text-xl"></i>
          <h2 class='font-bold text-xl'>
            Quick facts
          </h2>
        </div>
        <span class='font-medium text-sm'>
          Number of trolls:
          <span class='text-[#1D9AF1]'>
            <%= @users.length %>
          </span>
        </span>
        <span class='font-medium text-sm'>
          Number of microposts:
          <span class='text-[#1D9AF1]'>
            <%= @microposts.length %>
          </span>
        </span>
        <span class='font-medium text-sm'>
          Last micropost time:
          <span class='text-[#1D9AF1]'>
            <%= if @microposts.reverse[0].created_at.to_s.split(" ")[0] ==
                 Time.now.to_s.slice(0, 10)
              "Today, #{@microposts.reverse[0].created_at.to_s.split(" ").drop(1).join(" ")}"
            else
              micropost.created_at
            end %>
          </span>
        </span>
        <span class='font-medium text-sm'>
          Last troll to speak:
          <span class='text-[#1D9AF1]'>
            <%= User.find_by(id: @microposts.reverse[0].user_id).name %>
          </span>
        </span>
      </div>
      <div
        id="users"
        class="p-5 rounded-2xl border-[1px] border-solid border-gray-700 mt-4"
      >
        <div class='flex gap-2 items-center'>
          <i class="fa-regular fa-face-grin-squint-tears text-xl"></i>
          <h2 class='font-bold text-xl'>
            Your trolls
          </h2>
        </div>
        <% @users.reverse.each do |user| %>
          <div>
            <%= render user %>
          </div>
        <% end %>
        <%= link_to "Make troll",
        new_user_path,
        class:
          "text-white text-center inline-block font-medium text-md text-xl rounded-3xl py-2 px-5 bg-[#1D9AF1] mt-4 w-full" %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @user %>

    <div id="user_microposts" class="min-w-full pb-5">
      <h2 class='font-medium pb-2 text-md'>Posts:</h2>
      <% if @user_microposts.empty? %>
        <p class='text-white'>The user hasn't written any posts.</p>
      <% else %>
        <div class='rounded-lg bg-[#293449]'>
          <% @user_microposts.reverse.each do |user_micropost| %>
            <div class='px-2 py-5'>
              <p><%= user_micropost.content %></p>
              <p class='text-sm text-[#7DD3FC]'><%= user_micropost.created_at %></p>
              <div class='flex gap-2 font-medium'>
                <%= link_to "Edit",
                edit_micropost_path(user_micropost),
                class: "text-sm text-gray-500 underline pt-3 hover:text-[#1D9AF1]" %>
                <%= button_to "Destroy",
                user_micropost,
                method: :delete,
                class: "text-sm text-gray-500 underline pt-3 hover:text-red-800" %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= link_to "Edit this user",
    edit_user_path(@user),
    class: "mt-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
    <%= link_to "Back to users",
    users_path,
    class: "ml-2 rounded-lg py-3 px-5 bg-[#1E283A] inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this user",
      @user,
      method: :delete,
      class: "mt-2 rounded-lg py-3 px-5 bg-[#1E283A] font-medium" %>
    </div>
  </div>
</div>